// Generated by https://quicktype.io

export interface Total1ProductosID62Ac0332Cd3Dc3A23Be9C699NombreMANZANAEstadoTruePrecio12Costo15Minimo20Stock50__V0 {
    total:     number;
    productos: Producto[];
}

export interface Producto {
    _id:    string;
    nombre: string;
    estado: boolean;
    precio: number;
    costo:  number;
    minimo: number;
    stock:  number;
    __v:    number;
}
